name: forum_CD
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env  # 這裡的 env 環境指的是config env
    steps:
      - uses: actions/checkout@v2
      
      - name: forum_CD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script:
            pm2 stop forum || true
            pm2 delete forum || true
            cd ~
            if [ ! -d forum ]; then
                git clone git@github.com:sean-cy-2000/forum.git
            fi
            cd forum
            git pull origin main
            npm install
            echo "DB_NAME=${{ secrets.DB_NAME }}" > .env
            echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> .env
            echo "URI=${{ secrets.URI }}" >> .env
            authbind --deep pm2 start src/app.js --name forum