name: forum_CD
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env  # 這裡的 env 環境指的是config env
    steps:
      - uses: actions/checkout@v2
      
      - name: forum_CD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script:
            pm2 stop forum || true
            pm2 delete forum || true
            cd ~/forum
            git pull origin main
            npm install
            authbind --deep pm2 start src/app.js --name forum